### ISSUE TITLE
User Story 1, Deploy your application to Heroku

### ISSUE THREAD

**Issue by wrenisit** [wrenisit/paired_adopt_dont_shop#2]
[ ] done

User Story 1, Deploy your application to Heroku

As a visitor or user of the site
I will perform all user stories
By visiting the application on Heroku.
Localhost is fine for development, but
the application must be hosted on Heroku.

**Comment by LainMcGrath** [comment]
- Created app in Heroku and migrated database
- Confirmed app is functioning
- Added Wren as collaborator
